baseURL: https://bpetit.nce.re
DefaultContentLanguage: en
languageCode: "en-us"
languageName: English
title: "The cloud is a lie"
theme: "beautifulhugo"
Author:
  twitter: bpetit_
  linkedin: bepetit
  github: bpetit
  name: Benoit Petit
params:
  AuthorName: Benoit Petit
  GitHubUser: bpetit
  SidebarRecentLimit: 5
  selfHosted: true
  rss: false
permalinks:
  posts: /:year/:month/:title/
pygmentsCodeFences: true
pygmentsStyle: "native"
publishDir: docs
