baseURL: https://bpetit.nce.re
DefaultContentLanguage: en
languageCode: "en-us"
languageName: English
theme: "beautifulhugo"
Author:
  twitter: bpetit_
  linkedin: bepetit
  github: bpetit
  email: bpetit@b0rk.in
  goodreads: bpetit@b0rk.in
  name: Benoit Petit
params:
  AuthorName: Benoit Petit
  GitHubUser: bpetit
  SidebarRecentLimit: 5
  selfHosted: true
  rss: true
languages:
  en:
    title: "Benoit Petit"
    subtitle: "Pragmatic utopist, I build IT infrastructures. Striving for transparency and measurability. Nothing is virtual."
    languageName: English
    weight: 1
  fr:
    title: "Benoit Petit"
    subtitle: "Utopiste pragmatique, je construit des infrastructures informatiques. En quête de transparence et de mesurabilité. Rien n'est immatériel."
    languageName: Français
    weight: 2
permalinks:
  posts: /:year/:month/:title/
pygmentsCodeFences: true
pygmentsStyle: "native"
publishDir: docs
