baseURL: https://bpetit.nce.re
DefaultContentLanguage: en
languageCode: "en-us"
languageName: English
theme: "beautifulhugo"
Author:
  twitter: bpetit_
  linkedin: bepetit
  github: bpetit
  name: Benoit Petit
params:
  AuthorName: Benoit Petit
  GitHubUser: bpetit
  SidebarRecentLimit: 5
  selfHosted: true
  rss: true
languages:
  en:
    title: "&#9729; The cloud is a lie"
    weight: 1
  fr:
    title: "&#9729; Le nuage n'existe pas"
    weight: 2
permalinks:
  posts: /:year/:month/:title/
pygmentsCodeFences: true
pygmentsStyle: "native"
publishDir: docs
