baseURL: https://bpetit.nce.re
DefaultContentLanguage: en
languageCode: "en-us"
languageName: English
theme: "beautifulhugo"
params:
  AuthorName: Benoit Petit
  GitHubUser: bpetit
  SidebarRecentLimit: 5
  selfHosted: true
  rss: true
  author:
    mastodon: "mastodon.green/@bpetit"
    linkedin: bepetit
    github: bpetit
    gitlab: bpetit1
    bluesky: bpetit.bsky.social
    email: bpetit@nce.re
    name: Benoit Petit
languages:
  en:
    title: "Benoit Petit"
    homeTitle: "The cloud is a lie"
    subtitle: "IT infrastructures, environment, climate, social justice, not necessarily in that order."
    languageName: English
    weight: 1
  fr:
    title: "Benoit Petit"
    homeTitle: "Derrière les nuages"
    subtitle: "Infrastructures IT, environnement, climat, justice sociale, pas forcément dans cet ordre."
    languageName: Français
    weight: 2
permalinks:
  posts: /:year/:month/:title/
pygmentsCodeFences: true
pygmentsStyle: "native"
publishDir: docs
taxonomies:
  tag: tags
menu:
  main:
    - name: "Blog"
      url: ""
      weight: 1
    - name: "Data"
      url: "page/data/"
      weight: 2
