baseURL: https://bpetit.nce.re
DefaultContentLanguage: en
languageCode: "en-us"
languageName: English
theme: "beautifulhugo"
Author:
  twitter: bpetit_
  linkedin: bepetit
  github: bpetit
  email: bpetit@nce.re
  name: Benoit Petit
params:
  AuthorName: Benoit Petit
  GitHubUser: bpetit
  SidebarRecentLimit: 5
  selfHosted: true
  rss: true
languages:
  en:
    title: "Benoit Petit"
    homeTitle: "The cloud is just someone else's computer"
    subtitle: "ICT infrastructure engineer, focussed on sustainability. Nothing is virtual."
    languageName: English
    weight: 1
  fr:
    title: "Benoit Petit"
    homeTitle: "Bienvenue sur l'ordinateur de quelqu'un d'autre"
    subtitle: "Ingénieur infrastructure, spécialisé en durabilité et sobriété numérique. Rien n'est virtuel."
    languageName: Français
    weight: 2
permalinks:
  posts: /:year/:month/:title/
pygmentsCodeFences: true
pygmentsStyle: "native"
publishDir: docs
taxonomies:
  tag: tags
