baseURL: https://bpetit.github.io/blog
footnoteReturnLinkContents: ↩
params:
  AuthorName: Benoit Petit
  GitHubUser: bpetit
  SidebarRecentLimit: 5
permalinks:
  posts: /:year/:month/:title/
title: Tales of the late anticipation
publishDir: docs
theme: "beautifulhugo"
pygmentsCodeFences: true
pygmentsStyle: "native"
